// Gen 4 moves (Diamond/Pearl/Platinum/HeartGold/SoulSilver) added on top of FireRed's data.
// FireRed's move/species JSON (web/assets/data) is extracted ROM data and stays untouched: indexData()
// in data.js merges these into D.moves and into the species' learnsets / TM-HM / tutor lists at load.
//
// GEN4_MOVES (hand-written): how each move works here, mapped onto effects.js keys.
// gen4_data.js (generated by tools/gen4_moves_data.mjs from PokéAPI's CSVs): base stats, physical/special,
// and which Gen 1-3 species learn each move in Gen 4 (level-up at the Gen 4 level, TM/HM, tutor).
// Powers/accuracies are PokéAPI's current values. Physical/special lives in move_categories.js.

// key: [effect, secondary chance (%), description, extra fields]
export const GEN4_MOVES = {
  // ---- coverage attacks ----
  SHADOW_CLAW: ['HIGH_CRITICAL', 0, 'The user slashes with a sharp claw made from shadows. It has a high critical-hit ratio.'],
  NIGHT_SLASH: ['HIGH_CRITICAL', 0, 'The user slashes the foe the instant an opportunity arises. It has a high critical-hit ratio.'],
  PSYCHO_CUT: ['HIGH_CRITICAL', 0, 'The user tears at the foe with blades formed by psychic power. It has a high critical-hit ratio.'],
  STONE_EDGE: ['HIGH_CRITICAL', 0, 'The user stabs the foe with sharpened stones. It has a high critical-hit ratio.'],
  CROSS_POISON: ['POISON_TAIL', 10, 'A slashing attack with a poisonous blade. It has a high critical-hit ratio and may poison the foe.'],
  POISON_JAB: ['POISON_HIT', 30, 'The foe is stabbed with a tentacle or arm steeped in poison. It may also poison the foe.'],
  GUNK_SHOT: ['POISON_HIT', 30, 'The user shoots filthy garbage at the foe. It may also poison the foe.'],
  X_SCISSOR: ['HIT', 0, 'The user slashes at the foe by crossing its scythes or claws as if they were a pair of scissors.'],
  SEED_BOMB: ['HIT', 0, 'The user slams a barrage of hard-shelled seeds down on the foe from above.'],
  AQUA_TAIL: ['HIT', 0, 'The user attacks by swinging its tail as if it were a vicious wave in a raging storm.'],
  DRAGON_PULSE: ['HIT', 0, 'The foe is attacked with a shock wave generated by the user’s gaping mouth.'],
  POWER_GEM: ['HIT', 0, 'The user attacks with a ray of light that sparkles as if it were made of gemstones.'],
  POWER_WHIP: ['HIT', 0, 'The user violently whirls its vines or tentacles to harshly lash the foe.'],
  PLUCK: ['HIT', 0, 'The user stabs the foe with its beak.'],
  BUG_BITE: ['HIT', 0, 'The user bites the foe.'],
  DARK_PULSE: ['FLINCH_HIT', 20, 'The user releases a horrible aura imbued with dark thoughts. It may also make the foe flinch.'],
  AIR_SLASH: ['FLINCH_HIT', 30, 'The user attacks with a blade of air that slices even the sky. It may also make the foe flinch.'],
  ZEN_HEADBUTT: ['FLINCH_HIT', 20, 'The user focuses its willpower and rams its forehead into the foe. It may also make the foe flinch.'],
  IRON_HEAD: ['FLINCH_HIT', 30, 'The user slams the foe with its steel-hard head. It may also make the foe flinch.'],
  DRAGON_RUSH: ['FLINCH_HIT', 20, 'The user tackles the foe with menacing force. It may also make the foe flinch.'],
  BUG_BUZZ: ['SPECIAL_DEFENSE_DOWN_HIT', 10, 'The user vibrates its wings to make a damaging sound wave. It may also lower the foe’s SP. DEF.'],
  ENERGY_BALL: ['SPECIAL_DEFENSE_DOWN_HIT', 10, 'The user draws power from nature and fires it at the foe. It may also lower the foe’s SP. DEF.'],
  EARTH_POWER: ['SPECIAL_DEFENSE_DOWN_HIT', 10, 'The user makes the ground under the foe erupt with power. It may also lower the foe’s SP. DEF.'],
  FLASH_CANNON: ['SPECIAL_DEFENSE_DOWN_HIT', 10, 'The user gathers all its light energy and releases it at once. It may also lower the foe’s SP. DEF.'],
  FOCUS_BLAST: ['SPECIAL_DEFENSE_DOWN_HIT', 10, 'The user heightens its mental focus and unleashes its power. It may also lower the foe’s SP. DEF.'],
  MUD_BOMB: ['ACCURACY_DOWN_HIT', 30, 'The user launches a hard-packed mud ball at the foe. It may also lower the foe’s accuracy.'],
  MIRROR_SHOT: ['ACCURACY_DOWN_HIT', 30, 'The user looses a flash of energy from its polished body. It may also lower the foe’s accuracy.'],
  ROCK_CLIMB: ['CONFUSE_HIT', 20, 'The user attacks the foe with a vicious charge. It may also confuse the foe.'],
  DISCHARGE: ['PARALYZE_HIT', 30, 'A loose flare of electricity strikes the foe. It may also paralyze the foe.'],
  FORCE_PALM: ['PARALYZE_HIT', 30, 'The foe is attacked with a shock wave. It may also paralyze the foe.'],
  LAVA_PLUME: ['BURN_HIT', 30, 'An inferno of scarlet flames washes over the foe. It may also burn the foe.'],
  FIRE_FANG: ['FIRE_FANG', 10, 'The user bites with flame-cloaked fangs. It may also burn the foe or make it flinch.'],
  ICE_FANG: ['ICE_FANG', 10, 'The user bites with cold-infused fangs. It may also freeze the foe or make it flinch.'],
  THUNDER_FANG: ['THUNDER_FANG', 10, 'The user bites with electrified fangs. It may also paralyze the foe or make it flinch.'],
  OMINOUS_WIND: ['ALL_STATS_UP_HIT', 10, 'A repulsive wind strikes the foe. It may also raise all of the user’s stats.'],
  CHARGE_BEAM: ['SPECIAL_ATTACK_UP_HIT', 70, 'The user fires a concentrated bundle of electricity. It may also raise the user’s SP. ATK.'],
  AURA_SPHERE: ['ALWAYS_HIT', 0, 'The user looses a blast of aura power from deep within its body. This move never misses.', { accuracy: 0 }],
  MAGNET_BOMB: ['ALWAYS_HIT', 0, 'The user launches a steel bomb that sticks to the foe. This move never misses.', { accuracy: 0 }],
  DOUBLE_HIT: ['DOUBLE_HIT', 0, 'The user slams the foe with a tail or the like, hitting twice in a row.'],
  DRAIN_PUNCH: ['ABSORB', 0, 'An energy-draining punch that restores 20% of the user’s max HP.'],
  GRASS_KNOT: ['LOW_KICK', 0, 'The user snares the foe with grass and trips it. The heavier the foe, the greater the power.', { power: 1 }],
  BRINE: ['BRINE', 0, 'Doubles in power against a foe at half HP or less.'],

  // ---- priority ----
  BULLET_PUNCH: ['QUICK_ATTACK', 0, 'The user strikes the foe with tough punches as fast as bullets. It always strikes first.'],
  ICE_SHARD: ['QUICK_ATTACK', 0, 'The user flash-freezes chunks of ice and hurls them at the foe. It always strikes first.'],
  SHADOW_SNEAK: ['QUICK_ATTACK', 0, 'The user extends its shadow and attacks the foe from behind. It always strikes first.'],
  AQUA_JET: ['QUICK_ATTACK', 0, 'The user lunges at the foe at a speed that makes it almost invisible. It always strikes first.'],
  VACUUM_WAVE: ['QUICK_ATTACK', 0, 'The user whirls its fists to send a wave of pure vacuum at the foe. It always strikes first.'],
  SUCKER_PUNCH: ['SUCKER_PUNCH', 0, 'Strikes first, but fails unless the foe is about to use an attack (check its intent).'],

  // ---- retaliation ----
  PAYBACK: ['REVENGE', 0, 'An attack that doubles in power if the foe already hit your lead this turn.'],
  AVALANCHE: ['REVENGE', 0, 'An attack that doubles in power if the foe already hit your lead this turn.'],

  // ---- big hits with a cost ----
  BRAVE_BIRD: ['DOUBLE_EDGE', 0, 'The user tucks in its wings and charges from a low altitude. It also hurts the user a little.'],
  WOOD_HAMMER: ['DOUBLE_EDGE', 0, 'The user slams its rugged body into the foe. It also hurts the user a little.'],
  FLARE_BLITZ: ['FLARE_BLITZ', 10, 'The user cloaks itself in fire and charges the foe. It also hurts the user a little and may burn the foe.'],
  HEAD_SMASH: ['HEAD_SMASH', 0, 'The user attacks with a hazardous, full-power headbutt. It also hurts the user (1/4 of its max HP).'],
  CLOSE_COMBAT: ['CLOSE_COMBAT', 0, 'The user fights the foe up close without guarding itself. It lowers the user’s DEFENSE and SP. DEF.'],
  HAMMER_ARM: ['HAMMER_ARM', 0, 'The user swings and hits with its strong, heavy fist. It lowers the user’s SPEED.'],
  DRACO_METEOR: ['OVERHEAT', 100, 'Comets are summoned down from the sky. It also sharply lowers the user’s SP. ATK.'],
  LEAF_STORM: ['OVERHEAT', 100, 'The user whips up a storm of leaves around the foe. It also sharply lowers the user’s SP. ATK.'],
  GIGA_IMPACT: ['RECHARGE', 0, 'The user charges at the foe using every bit of its power. Its cards must recharge next turn.'],
  U_TURN: ['U_TURN', 0, 'The user attacks, and your next switch is free.'],

  // ---- support ----
  ROOST: ['RESTORE_HP', 0, 'The user lands and rests its body, restoring half of its max HP.'],
  ROCK_POLISH: ['SPEED_UP_2', 0, 'The user polishes its body to sharply raise its SPEED.'],
  NASTY_PLOT: ['SPECIAL_ATTACK_UP_2', 0, 'The user stimulates its brain by thinking bad thoughts. It sharply raises the user’s SP. ATK.'],
};

// Merge the moves and learnsets into D (called from data.js indexData()).
export function applyGen4Moves(D, { MOVES, LEARN }) {
  for (const [key, [effect, chance, desc, extra]] of Object.entries(GEN4_MOVES)) {
    const s = MOVES[key];
    if (!s || D.moves[key]) continue;
    D.moves[key] = {
      id: s.id, name: s.name, effect, power: s.power, type: s.type, accuracy: s.accuracy, pp: s.pp, chance,
      target: s.power ? 'SELECTED' : 'USER', priority: s.priority,
      flags: s.contact ? ['MAKES_CONTACT', 'PROTECT_AFFECTED', 'MIRROR_MOVE_AFFECTED'] : s.power ? ['PROTECT_AFFECTED', 'MIRROR_MOVE_AFFECTED'] : ['SNATCH_AFFECTED'],
      desc, gen: 4, ...(extra || {}),
    };
  }
  for (const [sp, { level, tmhm, tutor }] of Object.entries(LEARN)) {
    const s = D.species[sp];
    if (!s) continue;
    if (level?.length) {
      // Level 1 moves go first so they don't push out a low-level mon's usual moves; others slot in after
      // any FireRed moves at the same level (learnsets stay sorted, which defaultMoves() relies on).
      const ls = (s.learnset || []).slice();
      for (const [lvl, mv] of level) {
        if (!D.moves[mv] || ls.some(([, m]) => m === mv)) continue;
        let i = lvl <= 1 ? 0 : ls.findIndex(([l]) => l > lvl);
        if (i < 0) i = ls.length;
        ls.splice(i, 0, [lvl, mv]);
      }
      s.learnset = ls;
    }
    if (tmhm?.length) s.tmhm = [...(s.tmhm || []), ...tmhm.filter(m => D.moves[m] && !(s.tmhm || []).includes(m))];
    if (tutor?.length) s.tutor = [...(s.tutor || []), ...tutor.filter(m => D.moves[m] && !(s.tutor || []).includes(m))];
  }
}
