// Game data loaded from web/assets/data (generated by tools/extract_data.js from the decomp)
// plus Gen 3 formulas (stats, EXP curves, type chart, damage).

import { HOENN_PARTIES, HOENN_TRAINER_INFO, HOENN_TRAINERS } from './hoenn.js';
import { JOHTO_TRAINERS } from './johto.js';
import { SPECIAL_MOVES, PHYSICAL_MOVES } from './move_categories.js';
import { MOVE_DESC, ABILITY_DESC } from './text_overrides.js';
import { applyGen4Moves } from './gen4_moves.js';
import { RELICS, BALLS, CONSUMABLES } from './items.js';
import * as GEN4_DATA from './gen4_data.js';
import { loadGen4, applyGen4 } from './gen4.js';

export const D = {
  species: {}, moves: {}, types: { list: [], chart: {} }, items: {}, trainers: {},
  encounters: {}, abilities: {}, maps: {}, trainerClasses: {},
};

const FILES = {
  species: 'species.json', moves: 'moves.json', types: 'types.json', items: 'items.json',
  trainers: 'trainers.json', encounters: 'encounters.json', abilities: 'abilities.json',
  maps: 'maps.json', trainerClasses: 'trainer_classes.json',
};

// loader(name) -> parsed JSON. Browser passes a fetch-based loader, Node tests an fs-based one.
export async function loadData(loader) {
  await Promise.all(Object.entries(FILES).map(async ([k, f]) => {
    try { D[k] = await loader(f); } catch (e) { console.warn('data load failed', f, e); }
  }));
  // Gen 4 species (v0.4.0, gen4.js): their own file next to FireRed's species.json, merged in on every load.
  try { applyGen4(D, await loadGen4(loader)); } catch (e) { console.warn('data load failed', 'gen4', e); }
  indexData();
  return D;
}

export const byId = { species: [], moves: [] };
export const byDex = [];
// The national POKéDEX this game covers: #1-386 from FireRed's data, #387-493 from Gen 4 (gen4.js, v0.4.0).
export const DEX_MAX = 493;

function indexData() {
  // Gen 4 moves and learnsets (gen4_moves.js) on top of FireRed's data.
  applyGen4Moves(D, GEN4_DATA);
  for (const [key, s] of Object.entries(D.species)) {
    s.key = key;
    byId.species[s.id] = s;
    if (s.dex) byDex[s.dex] = s;
  }
  for (const [key, m] of Object.entries(D.moves)) { m.key = key; byId.moves[m.id] = m; }
  // Overworld uses and friendship flavor mean nothing here.
  const FIELD = /\s*(It can be used to cut down thin trees and grass|Can also be used for crossing water|Can also be used to move boulders|It can also smash cracked boulders|It can also be used to climb a waterfall|Use it to fly to any known town|Can also be used to exit dungeons|It also illuminates caves|It also attracts wild POK.MON|It can be used to heal an ally)\./g;
  const DESC = {
    RETURN: 'A full-power attack: always 102 power.',
    FRUSTRATION: 'A weak, bitter attack: always 40 power.',
    TELEPORT: 'Ends a wild battle immediately (no rewards). Does nothing against trainers.',
  };
  for (const [key, m] of Object.entries(D.moves)) {
    if (DESC[key]) m.desc = DESC[key];
    else if (m.desc) m.desc = m.desc.replace(FIELD, '').trim();
  }
  // Text rewritten for what moves and abilities actually do in this game (text_overrides.js).
  for (const [k, d] of Object.entries(MOVE_DESC)) if (D.moves[k]) D.moves[k].desc = d;
  for (const [k, d] of Object.entries(ABILITY_DESC)) if (D.abilities[k]) D.abilities[k].desc = d;
  // Combo upgrades are named after the combo they level up.
  const COMBO_ITEM_NAMES = { RED_SHARD: 'SINGLE UP', HP_UP: 'PAIR UP', PROTEIN: 'TWO PAIR UP', YELLOW_SHARD: 'TWO PAIR UP', IRON: 'TRIPLE UP',
    BLUE_SHARD: 'COVERAGE UP', CALCIUM: 'FULL HOUSE UP', ZINC: 'QUAD UP', CARBOS: 'PENTA UP' };
  for (const [k, n] of Object.entries(COMBO_ITEM_NAMES)) if (D.items[k]) D.items[k].name = n;
  // Held items with no FireRed item behind them (the legendary items) get an entry of their own.
  for (const [key, r] of Object.entries(RELICS)) if (r.name && !D.items[key]) D.items[key] = { name: r.name, desc: r.desc, price: 0, pocket: 'KEY_ITEMS', custom: true };
  for (const [key, c] of Object.entries(CONSUMABLES)) if (c.name && !D.items[key]) D.items[key] = { name: c.name, desc: c.desc, price: c.price, pocket: 'ITEMS', custom: true }; // (v0.4.0: the Gen 4 stones)
  for (const [key, b] of Object.entries(BALLS)) if (b.name && !D.items[key]) D.items[key] = { name: b.name, desc: b.desc, price: b.price, pocket: 'POKE_BALLS', custom: true }; // (KURT's APRICORN BALLS)
  for (const [key, it] of Object.entries(D.items)) it.key = key;
  for (const [key, t] of Object.entries(D.trainers)) t.key = key;
  // Hoenn teams (dummies in FireRed's data) authored in hoenn.js (v0.3.25: Emerald's), with their shown names and
  // Emerald portraits (pic; picFallback: the FireRed pic main.js shows when the optional Emerald art isn't there)
  for (const [key, party] of Object.entries(HOENN_PARTIES)) {
    const t = D.trainers[key];
    if (!t) continue;
    t.party = party; t.dummy = false; t.hoenn = true;
    Object.assign(t, HOENN_TRAINER_INFO[key] || {});
  }
  for (const [key, t] of Object.entries(HOENN_TRAINERS)) {
    D.trainers[key] = { female: false, items: [], maps: [], rematchOf: null, double: false, ...t, party: t.party.map(p => ({ ...p })), key, dummy: false, hoenn: true };
  }
  // Johto trainers (v0.1.1): FireRed has none, so they're whole trainer objects authored in johto.js
  for (const [key, t] of Object.entries(JOHTO_TRAINERS)) {
    D.trainers[key] = { female: false, items: [], maps: [], rematchOf: null, double: false, ...t, party: t.party.map(p => ({ ...p })), key, dummy: false, johto: true };
  }
}

// ---- Types -------------------------------------------------------------------------------
// Gen 3: the move's type decides physical vs special.
export const SPECIAL_TYPES = new Set(['FIRE', 'WATER', 'GRASS', 'ELECTRIC', 'PSYCHIC', 'ICE', 'DRAGON', 'DARK']);
export const isSpecial = type => SPECIAL_TYPES.has(type);
// Physical/special by move (modern rule); moves without an entry fall back to the Gen 3 type rule.
export const isSpecialMove = (key, type) => (SPECIAL_MOVES.has(key) ? true : PHYSICAL_MOVES.has(key) ? false : isSpecial(type));

export const TYPE_COLORS = {
  NORMAL: '#a8a878', FIGHTING: '#c03028', FLYING: '#a890f0', POISON: '#a040a0', GROUND: '#e0c068',
  ROCK: '#b8a038', BUG: '#a8b820', GHOST: '#705898', STEEL: '#b8b8d0', FIRE: '#f08030',
  WATER: '#6890f0', GRASS: '#78c850', ELECTRIC: '#f8d030', PSYCHIC: '#f85888', ICE: '#98d8d8',
  DRAGON: '#7038f8', DARK: '#705848', MYSTERY: '#68a090',
};

export function typeEffect(atkType, defTypes) {
  let m = 1;
  const row = D.types.chart[atkType] || {};
  for (const t of defTypes) if (row[t] !== undefined) m *= row[t];
  return m;
}

// ---- Stats -------------------------------------------------------------------------------
export function calcStat(base, iv, level, isHP, ev = 0) {
  const core = Math.floor(((2 * base + iv + Math.floor(ev / 4)) * level) / 100);
  return isHP ? core + level + 10 : core + 5;
}

export function monStats(speciesKey, level, ivs) {
  const s = D.species[speciesKey];
  const b = s.stats;
  if (speciesKey === 'SHEDINJA') return { hp: 1, atk: calcStat(b.atk, ivs.atk, level), def: calcStat(b.def, ivs.def, level), spa: calcStat(b.spa, ivs.spa, level), spd: calcStat(b.spd, ivs.spd, level), spe: calcStat(b.spe, ivs.spe, level) };
  return {
    hp: calcStat(b.hp, ivs.hp, level, true),
    atk: calcStat(b.atk, ivs.atk, level),
    def: calcStat(b.def, ivs.def, level),
    spa: calcStat(b.spa, ivs.spa, level),
    spd: calcStat(b.spd, ivs.spd, level),
    spe: calcStat(b.spe, ivs.spe, level),
  };
}

// Stat stage multipliers (-6..+6), Gen 3.
export function stageMult(stage) {
  stage = Math.max(-6, Math.min(6, stage));
  return stage >= 0 ? (2 + stage) / 2 : 2 / (2 - stage);
}
// Accuracy/evasion stage table (Gen 3 uses 3/3-based fractions).
const ACC_TABLE = [[33, 100], [36, 100], [43, 100], [50, 100], [60, 100], [75, 100], [1, 1], [133, 100], [166, 100], [2, 1], [233, 100], [133, 50], [3, 1]];
export function accStageMult(stage) {
  const [n, d] = ACC_TABLE[Math.max(-6, Math.min(6, stage)) + 6];
  return n / d;
}

// ---- EXP ---------------------------------------------------------------------------------
export function expForLevel(rate, n) {
  if (n <= 1) return 0;
  const n3 = n * n * n;
  switch (rate) {
    case 'FAST': return Math.floor((4 * n3) / 5);
    case 'MEDIUM_SLOW': return Math.max(0, Math.floor((6 * n3) / 5 - 15 * n * n + 100 * n - 140));
    case 'SLOW': return Math.floor((5 * n3) / 4);
    case 'ERRATIC':
      if (n <= 50) return Math.floor((n3 * (100 - n)) / 50);
      if (n <= 68) return Math.floor((n3 * (150 - n)) / 100);
      if (n <= 98) return Math.floor((n3 * Math.floor((1911 - 10 * n) / 3)) / 500);
      return Math.floor((n3 * (160 - n)) / 100);
    case 'FLUCTUATING':
      if (n <= 15) return Math.floor((n3 * (Math.floor((n + 1) / 3) + 24)) / 50);
      if (n <= 36) return Math.floor((n3 * (n + 14)) / 50);
      return Math.floor((n3 * (Math.floor(n / 2) + 32)) / 50);
    default: return n3; // MEDIUM_FAST
  }
}

// Gen 3 experience yield for defeating `species` at `level`.
export function expYield(speciesKey, level, trainer) {
  const s = D.species[speciesKey];
  let e = Math.floor(((s.expYield || 50) * level) / 7);
  if (trainer) e = Math.floor(e * 1.5);
  return Math.max(1, e);
}

// ---- Gen 3 damage formula (used for enemy attacks on your Pokémon) ------------------------
export function gen3Damage({ level, power, atk, def, stab, effect, burned, physical, rand = 1, crit = false }) {
  let a = atk, d = def;
  let dmg = Math.floor(Math.floor((Math.floor((2 * level) / 5) + 2) * power * a / d) / 50);
  if (burned && physical) dmg = Math.floor(dmg / 2);
  dmg += 2;
  if (crit) dmg *= 2;
  if (stab) dmg = Math.floor(dmg * 1.5);
  dmg = Math.floor(dmg * effect);
  dmg = Math.floor(dmg * rand);
  return effect === 0 ? 0 : Math.max(1, dmg);
}

// ---- Misc helpers ------------------------------------------------------------------------
export function displayName(s) {
  // FireRed names are upper case; keep that look but fix a few glyphs.
  return (s || '').replace(/\{PKMN\}/g, 'POKéMON');
}

export function speciesName(key) { return D.species[key]?.name || key; }
export function moveName(key) { return D.moves[key]?.name || key; }
export function itemName(key) { return D.items[key]?.name || key; }

export function bst(speciesKey) {
  const b = D.species[speciesKey].stats;
  return b.hp + b.atk + b.def + b.spa + b.spd + b.spe;
}

// Final evolution chain helpers
export function evolutionsOf(speciesKey) { return D.species[speciesKey]?.evolutions || []; }
export function isFullyEvolved(speciesKey) { return evolutionsOf(speciesKey).length === 0; }
export function baseForm(speciesKey) {
  let k = speciesKey, guard = 0;
  while (D.species[k]?.preEvolution && guard++ < 4) k = D.species[k].preEvolution;
  return k;
}
