// Description overrides for moves and abilities whose FireRed text doesn't match how they work in
// Kanto Spire (no overworld, PP, held items, allies or multi-turn charging; moves are cards).
// Every entry is based on effects.js / battle.js. Applied after data.js indexData().

export const MOVE_DESC = {
  // ---- field moves / flee ----
  TELEPORT: 'Ends a wild battle at once (no rewards). Against trainers and bosses, the foe hesitates instead.',
  ROAR: 'Scares off a wild foe, ending the battle (no rewards). Against trainers and bosses, the foe hesitates instead.',
  WHIRLWIND: 'Blows away a wild foe, ending the battle (no rewards). Against trainers and bosses, the foe hesitates instead.',
  FLY: 'Hits at once. If the foe acts after you, your lead flies out of reach and dodges its attack.',
  DIG: 'Hits at once. If the foe acts after you, your lead burrows underground and dodges its attack.',
  DIVE: 'Hits at once. If the foe acts after you, your lead dives underwater and dodges its attack.',
  BOUNCE: 'Hits at once. If the foe acts after you, your lead springs out of reach and dodges its attack.',

  // ---- charge / rampage / delayed moves that resolve in one turn ----
  SOLAR_BEAM: "Blasts the foe at once, then the user's cards rest next turn. No rest in sunlight; weakened in rain.",
  RAZOR_WIND: "Blades of wind hit at once with a high critical-hit ratio, then the user's cards rest next turn.",
  SKULL_BASH: "Hits at once and raises the user's DEFENSE, then the user's cards rest next turn.",
  SKY_ATTACK: "Hits at once with a high critical-hit ratio and may make the foe flinch. The user's cards rest next turn.",
  THRASH: 'The user rampages for one big hit. Afterward it may become confused (50% chance).',
  PETAL_DANCE: 'The user attacks with a storm of petals. Afterward it may become confused (50% chance).',
  OUTRAGE: 'The user thrashes about for one big hit. Afterward it may become confused (50% chance).',
  UPROAR: 'The user attacks in an uproar. No POKéMON can fall asleep for three turns.',
  FUTURE_SIGHT: 'A psychic attack that strikes the foe right away.',
  DOOM_DESIRE: 'A blast of light that strikes the foe right away.',
  BIDE: 'Strikes back at once for 2x the damage the foe dealt your lead this turn.',
  ROLLOUT: 'Power doubles each hand in a row it is played (up to 16x). Doubled again after DEFENSE CURL.',
  ICE_BALL: 'Power doubles each hand in a row it is played (up to 16x). Doubled again after DEFENSE CURL.',
  FURY_CUTTER: 'Power doubles each time it is played in consecutive hands (up to 16x).',
  RAGE: 'Gains 10 power each time it is used in the battle.',

  // ---- retaliation / timing ----
  COUNTER: 'Strikes back at a foe that already hit your lead this turn, physical or special.',
  MIRROR_COAT: 'Strikes back at a foe that already hit your lead this turn, special or physical.',
  REVENGE: 'An attack that doubles in power if the foe already hit your lead this turn.',
  FOCUS_PUNCH: 'A 150-power punch that fails if the foe already hit your lead this turn.',
  VITAL_THROW: 'A sure-footed throw that never misses.',
  PURSUIT: 'A plain 40-power attack here. Nobody switches out mid-turn.',
  FAKE_OUT: 'A quick strike. On the first turn of battle it always makes the foe flinch.',
  PROTECT: 'Shields the user from all of the foe’s moves this turn. Used on back-to-back turns, it is likelier to fail (100%, 50%, 25%...).',
  DETECT: 'Shields the user from all of the foe’s moves this turn. Used on back-to-back turns, it is likelier to fail (100%, 50%, 25%...).',
  ENDURE: 'The user survives any hit this turn with at least 1 HP. Used on back-to-back turns, it is likelier to fail (100%, 50%, 25%...).',

  // ---- fixed / special damage ----
  SONIC_BOOM: 'A shock wave that always deals 20 damage, no matter the stats.',
  DRAGON_RAGE: 'A shock wave that always deals 40 damage, no matter the stats.',
  SEISMIC_TOSS: "Deals damage equal to the user's level, ignoring stats and type matchups.",
  NIGHT_SHADE: "Deals damage equal to the user's level, ignoring stats and type matchups.",
  GUILLOTINE: 'Knocks out the foe if it hits. Fails on bosses, elites, legendaries, higher-level foes and STURDY.',
  HORN_DRILL: 'Knocks out the foe if it hits. Fails on bosses, elites, legendaries, higher-level foes and STURDY.',
  FISSURE: 'Knocks out the foe if it hits. Fails on bosses, elites, legendaries, higher-level foes and STURDY.',
  SHEER_COLD: 'Knocks out the foe if it hits. Fails on bosses, elites, legendaries, higher-level foes and STURDY.',
  SUPER_FANG: "Halves the foe's remaining HP (1/8 against bosses and elites). Works once per hand.",
  ENDEAVOR: "Cuts the foe's HP down to the user's HP percentage (at most 25% of max HP off bosses). Once per hand.",
  FALSE_SWIPE: 'A restrained attack. The hand it is in always leaves the foe with at least 1 HP.',
  SELF_DESTRUCT: 'The user blows up for double damage and faints at once. Cards after it in the hand fizzle.',
  EXPLOSION: 'The user explodes for double damage and faints at once. Cards after it in the hand fizzle.',
  MAGNITUDE: 'A ground-shaking attack whose power varies at random from 10 to 150.',
  PRESENT: 'The foe is given a booby-trapped gift that hits with 40, 80 or 120 power.',
  BEAT_UP: 'Power grows with every healthy, status-free POKéMON in your party.',
  SMELLING_SALT: 'Doubly effective on a paralyzed foe.',
  EARTHQUAKE: 'A powerful earthquake that strikes the foe.',
  SWIFT: 'Star-shaped rays that never miss are fired at the foe.',
  STRUGGLE: 'A desperate attack that also hurts the user a little.',

  // ---- draining ----
  ABSORB: "An attack that restores 12% of the user's max HP.",
  MEGA_DRAIN: "A tough attack that restores 12% of the user's max HP.",
  LEECH_LIFE: "An attack that restores 12% of the user's max HP.",
  GIGA_DRAIN: "A harsh attack that restores 20% of the user's max HP.",
  DREAM_EATER: "Only works on a sleeping foe. Restores 30% of the user's max HP.",

  // ---- calling moves ----
  METRONOME: 'Waggles a finger and turns into a random attacking move.',
  ASSIST: 'Turns into a random attacking move.',
  MIRROR_MOVE: 'Copies the move the foe used last (PECK if it has not moved yet).',
  NATURE_POWER: 'Turns into SWIFT, a 60-power attack that never misses.',
  SLEEP_TALK: 'Turns into a random attack of up to 60 power. Can be played even while asleep.',
  SNORE: 'An attack that can be played even while asleep. It may make the foe flinch.',

  // ---- held items / money ----
  THIEF: 'An attack that also swipes some cash, paid out if you win.',
  COVET: 'A cutely executed attack that also swipes some cash, paid out if you win.',
  KNOCK_OFF: "Knocks away the foe's REFLECT and LIGHT SCREEN.",
  TRICK: 'A sly trick. Draw 2 extra cards next turn.',
  RECYCLE: 'Recycles your discards. Draw 2 extra cards next turn.',

  // ---- copying / type changes / allies: card draw ----
  FOLLOW_ME: 'The user draws attention to itself. Draw 2 extra cards next turn.',
  SKILL_SWAP: 'A burst of psychic power. Draw 2 extra cards next turn.',
  ROLE_PLAY: 'The user studies the foe. Draw 2 extra cards next turn.',
  MIMIC: 'Copies the move the foe is about to use: adds a one-use card of it to your hand.',
  YAWN: 'The foe grows drowsy and falls asleep at the end of the turn, so it skips its next move. Fails if the foe can’t fall asleep.',
  TRANSFORM: 'The user turns into the foe: adds one-use cards of 2 of its moves to your hand.',
  CONVERSION: 'The user reshapes itself. Draw 1 extra card next turn.',
  CONVERSION_2: 'The user reshapes itself. Draw 1 extra card next turn.',
  CAMOUFLAGE: 'The user blends in. Draw 1 extra card next turn.',
  SKETCH: 'Sketches the move the foe is about to use: adds a one-use card of it to your hand.',
  HELPING_HAND: "This hand deals 1.5x damage.",

  // ---- PP / ability / switching moves reworked ----
  SPITE: "A spiteful move that lowers the foe's ATTACK stat.",
  IMPRISON: "The user seals the foe's power, lowering its SP. ATK stat.",
  GRUDGE: 'If the user faints this turn, the foe faints too (bosses lose 40% of their HP).',
  DESTINY_BOND: 'If the user faints this turn, the foe faints too (bosses lose 40% of their HP).',
  TORMENT: 'Has no effect here.',
  DISABLE: "The foe's next move is blocked.",
  ENCORE: 'The foe loses its next move.',
  MAGIC_COAT: 'The next status move the foe aims at you is reflected back at it.',
  SNATCH: 'Works like MAGIC COAT: the next status move the foe aims at you is reflected back.',
  MEAN_LOOK: 'Has no effect when you use it. If a foe uses it, you can no longer run away.',
  SPIDER_WEB: 'Has no effect when you use it. If a foe uses it, you can no longer run away.',
  BLOCK: 'Has no effect when you use it. If a foe uses it, you can no longer run away.',
  BATON_PASS: "Your next switch is free, and the new lead keeps the old lead's effects (good and bad).",
  INGRAIN: 'The user lays roots that restore 1/16 of max HP every turn.',
  PERISH_SONG: 'The foe faints after three turns (bosses lose 30% of max HP). If a foe sings it, switch your lead out.',
  TEETER_DANCE: 'A wobbly dance that confuses the foe.',
  ATTRACT: 'The foe becomes infatuated for three turns and may not attack. Bosses, elites and legendaries are unmoved.',

  // ---- healing / field effects ----
  MORNING_SUN: "Restores half of the user's max HP.",
  SYNTHESIS: "Restores half of the user's max HP.",
  MOONLIGHT: "Restores half of the user's max HP.",
  REST: 'The user fully restores HP and cures its status, then falls asleep for a short while.',
  PAIN_SPLIT: 'The user and the foe share their pain: both end up at the average of their HP percentages.',
  SUBSTITUTE: "The user spends 1/4 of its max HP on a decoy that blocks status conditions and absorbs the foe's next hit.",
  MIST: "The user's side is shrouded in mist, blocking stat cuts from the foe for five turns.",
  MUD_SPORT: "Halves the damage of ELECTRIC-type attacks aimed at the user's side.",
  WATER_SPORT: "Halves the damage of FIRE-type attacks aimed at the user's side.",
  FORESIGHT: "Negates the foe's evasion boosts and lets NORMAL and FIGHTING moves hit GHOST types.",
  ODOR_SLEUTH: "Negates the foe's evasion boosts and lets NORMAL and FIGHTING moves hit GHOST types.",
  SECRET_POWER: 'An attack that may paralyze the foe.',

  // ---- friendship (already overridden in data.js; repeated so this file is the single source) ----
  RETURN: 'A full-power attack: always 102 power.',
  FRUSTRATION: 'A weak, bitter attack: always 40 power.',
};

export const ABILITY_DESC = {
  // ---- does nothing here ----
  STENCH: 'No effect in battle here.',
  BATTLE_ARMOR: 'No effect in battle here.',
  SHELL_ARMOR: 'No effect in battle here.',
  DAMP: 'No effect in battle here.',
  OBLIVIOUS: 'No effect in battle here.',
  CLOUD_NINE: 'No effect in battle here.',
  AIR_LOCK: 'No effect in battle here.',
  COLOR_CHANGE: 'No effect in battle here.',
  SUCTION_CUPS: 'No effect in battle here.',
  LIGHTNING_ROD: 'No effect in battle here.',
  SERENE_GRACE: 'No effect in battle here.',
  ILLUMINATE: 'No effect in battle here.',
  TRACE: 'No effect in battle here.',
  MAGNET_PULL: 'No effect in battle here.',
  SOUNDPROOF: 'No effect in battle here.',
  CACOPHONY: 'No effect in battle here.',
  PRESSURE: 'No effect in battle here.',
  EARLY_BIRD: 'No effect in battle here.',
  PICKUP: 'No effect in battle here.',
  CUTE_CHARM: 'No effect in battle here.',
  PLUS: 'No effect in battle here.',
  MINUS: 'No effect in battle here.',
  FORECAST: 'No effect in battle here.',
  STICKY_HOLD: 'No effect in battle here.',
  MARVEL_SCALE: 'No effect in battle here.',
  LIQUID_OOZE: 'No effect in battle here.',
  ROCK_HEAD: 'No effect in battle here.',

  // ---- works differently ----
  VOLT_ABSORB: 'ELECTRIC moves have no effect on it.',
  WATER_ABSORB: 'WATER moves have no effect on it.',
  FLASH_FIRE: 'FIRE moves have no effect on it.',
  STURDY: 'Immune to one-hit KO moves. Your POKéMON with it also survive a hit from full HP.',
  SHIELD_DUST: 'A foe with it ignores the added effects of your attacks. No effect for your POKéMON.',
  SHADOW_TAG: 'You cannot run from a wild foe with this ability.',
  ARENA_TRAP: 'You cannot run from a wild foe with this ability.',
  RUN_AWAY: 'With it in the lead, you always get away from wild battles (unless trapped).',
  NATURAL_CURE: 'Cures its status problem when you switch it out.',
  GUTS: 'Your POKéMON only: ups ATTACK and ignores the burn penalty while it has a status problem.',
  CLEAR_BODY: 'Prevents the foe from lowering its stats.',
  WHITE_SMOKE: 'Prevents the foe from lowering its stats.',
};
