#!/usr/bin/env node
// Generates web/src/game/gen4_data.js: base data for the Gen 4 moves listed in web/src/game/gen4_moves.js
// and which Gen 1-3 species (national dex <= 386) learn them in Diamond/Pearl, Platinum or
// HeartGold/SoulSilver by level-up, TM/HM or move tutor. Source: PokéAPI's CSV dump.
//
//   node tools/gen4_moves_data.mjs [csvDir]     # csvDir defaults to downloading from GitHub
//
// Level-up levels come from Platinum, else HGSS, else DP. A move a species gets by level-up is not
// also listed as a TM/tutor move for it.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { GEN4_MOVES } from '../web/src/game/gen4_moves.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/';
const dir = process.argv[2];

async function csv(name) {
  const txt = dir ? fs.readFileSync(path.join(dir, name + '.csv'), 'utf8') : await (await fetch(SRC + name + '.csv')).text();
  const [head, ...rows] = txt.trim().split(/\r?\n/);
  const keys = head.split(',');
  return rows.map(l => { const v = l.split(','); const o = {}; keys.forEach((k, i) => { o[k] = v[i]; }); return o; });
}

const species = JSON.parse(fs.readFileSync(path.join(ROOT, 'web/assets/data/species.json'), 'utf8'));
const byDex = {};
for (const [k, s] of Object.entries(species)) if (s.dex) byDex[s.dex] = k;

const [moves, names, types, flagMap, pm] = await Promise.all(['moves', 'move_names', 'types', 'move_flag_map', 'pokemon_moves'].map(csv));
const typeName = Object.fromEntries(types.map(t => [t.id, t.identifier.toUpperCase()]));
const enName = Object.fromEntries(names.filter(n => n.local_language_id === '9').map(n => [n.move_id, n.name]));
const contact = new Set(flagMap.filter(f => f.move_flag_id === '1').map(f => f.move_id));
const keyOf = m => m.identifier.toUpperCase().replace(/-/g, '_');

const MOVES = {}, idToKey = {};
for (const m of moves) {
  const key = keyOf(m);
  if (!GEN4_MOVES[key]) continue;
  if (m.generation_id !== '4') throw new Error(`${key} is not a Gen 4 move`);
  idToKey[m.id] = key;
  MOVES[key] = {
    id: +m.id, name: enName[m.id].toUpperCase(), type: typeName[m.type_id], power: +m.power || 0,
    accuracy: +m.accuracy || 0, pp: +m.pp, priority: +m.priority, special: m.damage_class_id === '3', status: m.damage_class_id === '1',
    contact: contact.has(m.id),
  };
}
const missing = Object.keys(GEN4_MOVES).filter(k => !MOVES[k]);
if (missing.length) throw new Error('not in PokéAPI: ' + missing.join(' '));

// version groups: 8 diamond-pearl, 9 platinum, 10 heartgold-soulsilver. methods: 1 level-up, 3 tutor, 4 machine
const VG_PREF = { 9: 0, 10: 1, 8: 2 };
const lvl = {}, tm = {}, tutor = {};
for (const r of pm) {
  const dex = +r.pokemon_id, key = idToKey[r.move_id];
  if (!key || dex > 386 || !(r.version_group_id in VG_PREF) || !byDex[dex]) continue;
  const sp = byDex[dex];
  if (r.pokemon_move_method_id === '1') {
    const cur = (lvl[sp] ??= {})[key], pref = VG_PREF[r.version_group_id];
    if (!cur || pref < cur.pref || (pref === cur.pref && +r.level < cur.level)) lvl[sp][key] = { level: Math.max(1, +r.level), pref };
  } else if (r.pokemon_move_method_id === '4') (tm[sp] ??= new Set()).add(key);
  else if (r.pokemon_move_method_id === '3') (tutor[sp] ??= new Set()).add(key);
}

const LEARN = {};
for (const sp of Object.keys(species)) {
  const level = Object.entries(lvl[sp] || {}).map(([k, v]) => [v.level, k]).sort((a, b) => a[0] - b[0] || a[1].localeCompare(b[1]));
  const lv = new Set(level.map(([, k]) => k));
  const t = [...(tm[sp] || [])].filter(k => !lv.has(k)).sort();
  const u = [...(tutor[sp] || [])].filter(k => !lv.has(k) && !t.includes(k)).sort();
  if (level.length || t.length || u.length) LEARN[sp] = { level, tmhm: t, tutor: u };
}

const out = [
  '// GENERATED by tools/gen4_moves_data.mjs from PokéAPI (https://github.com/PokeAPI/pokeapi) - do not edit.',
  '// Gen 4 move data and the Gen 1-3 species that learn them in DPPt/HGSS. See gen4_moves.js.',
  'export const MOVES = {',
  ...Object.entries(MOVES).sort((a, b) => a[1].id - b[1].id).map(([k, m]) => `  ${k}: ${JSON.stringify(m)},`),
  '};',
  'export const LEARN = {',
  ...Object.entries(LEARN).sort((a, b) => species[a[0]].dex - species[b[0]].dex).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`),
  '};',
  '',
];
fs.writeFileSync(path.join(ROOT, 'web/src/game/gen4_data.js'), out.join('\n'));
const nLevel = Object.values(LEARN).reduce((a, v) => a + v.level.length, 0), nTm = Object.values(LEARN).reduce((a, v) => a + v.tmhm.length, 0), nTut = Object.values(LEARN).reduce((a, v) => a + v.tutor.length, 0);
console.log(`${Object.keys(MOVES).length} moves, ${Object.keys(LEARN).length} species: ${nLevel} level-up, ${nTm} TM/HM, ${nTut} tutor entries`);
console.log('special:', Object.keys(MOVES).filter(k => MOVES[k].special).join(' '));
console.log('physical:', Object.keys(MOVES).filter(k => !MOVES[k].special && !MOVES[k].status).join(' '));
const unlearned = Object.keys(MOVES).filter(k => !Object.values(LEARN).some(v => v.level.some(([, m]) => m === k) || v.tmhm.includes(k) || v.tutor.includes(k)));
if (unlearned.length) console.log('learned by no Gen 1-3 species:', unlearned.join(' '));
