// Rebuilds web/src/vendor/convex-browser.js: Convex's browser WebSocket client (ConvexClient, from the convex npm
// package in node_modules) as ONE minified ES module, so the unbundled game can import it (co-op live updates,
// web/src/net/coopnet.js). Run after upgrading the convex package:  node tools/vendor_convex.cjs
const path = require('path');
const root = path.join(__dirname, '..');
const version = require(path.join(root, 'node_modules/convex/package.json')).version;
require('esbuild').buildSync({
  stdin: { contents: "export { ConvexClient } from 'convex/browser';", resolveDir: root, loader: 'js' },
  bundle: true, format: 'esm', platform: 'browser', target: 'es2020', minify: true, legalComments: 'none',
  banner: { js: `// convex ${version} browser client (ConvexClient), Apache-2.0, https://github.com/get-convex/convex-js. Generated by tools/vendor_convex.cjs: do not edit.` },
  outfile: path.join(root, 'web/src/vendor/convex-browser.js'),
});
console.log('wrote web/src/vendor/convex-browser.js (convex ' + version + ')');
